[package]
name = "wavy"
version = "0.1.0"
edition = "2021"

[dependencies]
libm="0.2"
num-traits = { version = "0.2", default-features = false }

[dev-dependencies]
plotters = "^0.3.1"
float-cmp = "0.9.0"