name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule: [cron: "40 1 * * 5"]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  build:
    strategy:
      matrix:
        build_args:
          ["", "--no-default-features --features libm", "--features libm"]
        toolchain: ["stable", "1.60"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: "clippy"
      - name: Cargo check
        if: matrix.toolchain != 'stable'
        run: cargo check --verbose ${{ matrix.build_args }}
      - name: Clipy lints
        if: matrix.toolchain == 'stable'
        run: cargo clippy --all-targets --verbose ${{ matrix.build_args }} -- -Dclippy::all -Dclippy::pedantic
      - name: Run tests
        if: matrix.toolchain == 'stable'
        run: cargo test --verbose ${{ matrix.build_args }}
      - name: Build examples
        if: matrix.toolchain == 'stable'
        run: cargo build --verbose --examples ${{ matrix.build_args }}

  miri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@miri
      - run: cargo miri test --verbose
        env:
          MIRIFLAGS: -Zmiri-strict-provenance

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: "rustfmt"
      - name: Check code formatting
        run: cargo fmt -- --check

  # This job should depend on all required jobs.
  # We will make Bors watch this job to tell whether to merge or not.
  done:
    name: Done
    needs: [build, miri, fmt]
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: echo Done

  outdated:
    name: Outdated
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/install@cargo-outdated
      - run: cargo outdated --workspace --exit-code 1
